name: Check tag
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script with a secret
        env:
          CYPCODE_ORG_NAME: ${{ secrets.CYPCODE_ORG_NAME }}
        run: |
          echo "The token is now available as an env var, but GitHub will mask it in logs."
